import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import ReduxProvider from '@/redux/ReduxProvider'
import TopMenu from '@/components/TopMenu'
import { AlertProvider } from '@/components/AlertContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const nextAuthSession = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <NextAuthProvider session={nextAuthSession}>
          <AlertProvider>
            <main >
              {children}
            </main>
            </AlertProvider>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
