import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/utils/authOption'
import NextAuthProvider from '@/providers/NextAuthProvider'
import ReduxProvider from '@/redux/ReduxProvider'
import TopMenu from '@/components/TopMenu'
import { ThemeProvider } from '@emotion/react'
import { theme } from '@/components/MuiThemeProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const nextAuthSession = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <NextAuthProvider session={nextAuthSession}>
            {/* <ThemeProvider theme={theme}> */}
              {/* <AlertProvider> */}
                <main >
                  {children}
                </main>
              {/* </AlertProvider> */}
            {/* </ThemeProvider> */}
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
